import './styles.css';
import lashbyLogo from './assets/lashby-logo.jpg';
import {icons,createIcons} from 'lucide';
import {configured,supabase,recoveryRequested,authRedirectError,requestPasswordReset,updatePassword,signIn,signOut,session,loadAppData,createProduct,createSale,createStockReceipt,createExpense,createCustomer,createAppointment,createCourse,createEnrollment,openCash,closeCash,createVariant,payExpense,voidExpense,completeLotCost,voidSale,voidStockReceipt} from './api.js';
import {money,calculateSale,todayISO,businessDate,periodSummary,cashExpected,argentinaTimestamp} from './core.js';

const app=document.querySelector('#app');
const state={route:'dashboard',data:null,cart:[],payments:[{method:'CASH',amount:0}],modal:null,search:''};
const nav=[['dashboard','LayoutDashboard','Resumen'],['sale','ShoppingBag','Nueva venta'],['sales','Receipt','Historial de ventas'],['products','Package','Productos'],['stock','Boxes','Stock'],['cash','WalletCards','Caja'],['expenses','ReceiptText','Costos y gastos'],['appointments','CalendarDays','Turnos'],['students','GraduationCap','Alumnas'],['reports','ChartNoAxesCombined','Informes'],['audit','ShieldCheck','Auditoría']];
const icon=(name)=>`<i data-lucide="${name}"></i>`;
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function hydrateIcons(){createIcons({icons});}
function toast(message){document.body.insertAdjacentHTML('beforeend',`<div class="toast">${esc(message)}</div>`);setTimeout(()=>document.querySelector('.toast')?.remove(),2800)}
function loginView(){app.innerHTML=`<main class="login-shell"><section class="login-brand"><div class="brand-mark"><img class="brand-logo" src="${lashbyLogo}" alt="Logo de Lashby Beauty Eyelashes" width="96" height="96"><span>Lashby Academia</span></div><div class="login-copy"><p class="eyebrow">Gestión comercial</p><h1>Tu negocio,<br><span>bien organizado.</span></h1><p>Ventas, stock FIFO, caja, clientas y rentabilidad en un solo lugar.</p></div><small>Uso interno · Argentina · ARS</small></section><section class="login-panel"><form class="login-card" id="login-form"><span class="eyebrow">Acceso seguro</span><h2>Bienvenida</h2><p>Ingresá con tu usuario de Lashby.</p><div class="field"><label for="email">Correo electrónico</label><input id="email" name="email" type="email" required autocomplete="username" placeholder="nombre@correo.com"></div><div class="field"><label for="password">Contraseña</label><input id="password" name="password" type="password" required autocomplete="current-password" placeholder="Tu contraseña"></div><button class="btn btn-primary btn-block" type="submit">Ingresar</button>${!configured?`<div class="login-note"><strong>Vista de desarrollo:</strong> Supabase todavía no está conectado. Podés entrar para recorrer el sistema; los datos visibles son demostrativos y no se guardan.</div><button class="btn btn-soft btn-block" id="demo-login" type="button" style="margin-top:10px">Entrar en modo demostración</button>`:''}</form></section></main>`;hydrateIcons();document.querySelector('#login-form').addEventListener('submit',handleLogin);if(configured){const button=document.createElement('button');button.type='button';button.className='btn btn-soft btn-block';button.style.marginTop='12px';button.textContent='Crear o recuperar contraseña';button.onclick=resetRequestView;document.querySelector('#login-form').append(button);}document.querySelector('#demo-login')?.addEventListener('click',()=>boot(true));}
async function handleLogin(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await signIn(f.get('email'),f.get('password'));await boot();}catch(err){toast(err.message||'No se pudo iniciar sesión');}}
async function boot(demo=false){try{state.data=await loadAppData();renderShell();}catch(err){loginView();toast(err.message);}}

function renderShell(){const role=state.data.profile?.role||'VENDEDOR';app.innerHTML=`<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand-mark"><img class="brand-logo" src="${lashbyLogo}" alt="Logo de Lashby Beauty Eyelashes" width="96" height="96"><span>Lashby Gestión</span></div><nav class="nav">${nav.map(([r,i,l])=>`<button data-route="${r}" class="${state.route===r?'active':''}">${icon(i)}<span>${l}</span></button>`).join('')}</nav><div class="sidebar-foot"><div class="user-name">${esc(state.data.profile?.full_name||'Usuario')}</div><div class="user-role">${esc(role)}</div><button class="nav logout" id="logout">${icon('LogOut')} Salir</button></div></aside><section class="main"><header class="topbar"><div style="display:flex;align-items:center;gap:12px"><button class="mobile-menu" id="menu">${icon('Menu')}</button><img class="topbar-logo" src="${lashbyLogo}" alt="Lashby" width="40" height="40"><h1 class="page-title" id="page-title"></h1></div><div class="top-actions"><span class="today">${new Intl.DateTimeFormat('es-AR',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</span><button class="btn btn-soft" data-route="sale">${icon('Plus')} Nueva venta</button></div></header><main class="content" id="content"></main><nav class="bottom-nav hidden">${nav.slice(0,4).map(([r,i,l])=>`<button data-route="${r}">${icon(i)}<span>${l}</span></button>`).join('')}</nav></section></div><div id="modal-root"></div>`;bindShell();renderRoute();}
function bindShell(){document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>{state.route=b.dataset.route;document.querySelector('#sidebar')?.classList.remove('open');renderShell();}));document.querySelector('#menu').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#logout').onclick=async()=>{await signOut();loginView()};}
function renderRoute(){const pages={dashboard:dashboardPage,sale:salePage,sales:salesHistoryPage,products:productsPage,stock:stockPage,cash:cashPage,expenses:expensesPage,appointments:appointmentsPage,students:studentsPage,reports:reportsPage,audit:auditPage};document.querySelector('#page-title').textContent=nav.find(n=>n[0]===state.route)?.[2]||'';pages[state.route]();hydrateIcons();}
const page=(html)=>document.querySelector('#content').innerHTML=html;
const dailySales=()=>state.data.sales.filter(s=>s.status!=='VOID'&&s.created_at&&businessDate(s.created_at)===todayISO());
function dashboardPage(){const sales=dailySales();const total=sales.reduce((a,s)=>a+Number(s.total),0);const units=sales.flatMap(s=>s.sale_lines||[]).reduce((a,l)=>a+Number(l.quantity||0),0);const low=state.data.products.filter(p=>Number(p.stock)<=Number(p.min_stock));page(`<div class="page-head"><div><h2>Resumen del día</h2><p>La actividad de Lashby, de un vistazo.</p></div>${state.data.demo?'<span class="badge warn">Datos demostrativos</span>':''}</div><section class="metric-grid"><article class="metric"><div class="metric-top"><span>Ventas</span><span class="metric-icon">${icon('TrendingUp')}</span></div><div class="metric-value">${money(total)}</div><div class="metric-note">${sales.length} operaciones</div></article><article class="metric"><div class="metric-top"><span>Ticket promedio</span><span class="metric-icon">${icon('Receipt')}</span></div><div class="metric-value">${money(sales.length?total/sales.length:0)}</div><div class="metric-note">Venta promedio del día</div></article><article class="metric"><div class="metric-top"><span>Unidades vendidas</span><span class="metric-icon">${icon('PackageCheck')}</span></div><div class="metric-value">${units}</div><div class="metric-note">Productos físicos</div></article><article class="metric"><div class="metric-top"><span>Stock bajo</span><span class="metric-icon">${icon('TriangleAlert')}</span></div><div class="metric-value">${low.length}</div><div class="metric-note">Requieren atención</div></article></section><section class="grid-2"><article class="card"><div class="card-head"><h3>Ventas de la semana</h3><span class="muted">ARS</span></div>${chartHtml()}</article><article class="card"><div class="card-head"><h3>Alertas de stock</h3><button class="btn btn-soft" data-go="stock">Ver stock</button></div>${low.length?low.map(p=>`<div class="cart-line"><div><strong>${esc(p.name)}</strong><div class="muted">${esc(p.code)}</div></div><span class="badge ${Number(p.stock)<0?'danger':'warn'}">${p.stock} u.</span></div>`).join(''):`<div class="empty"><strong>Stock en orden</strong>No hay productos bajo el mínimo.</div>`}</article></section>`);document.querySelector('[data-go="stock"]')?.addEventListener('click',()=>{state.route='stock';renderShell()});}
function chartHtml(){const end=todayISO();const dates=Array.from({length:7},(_,i)=>{const d=new Date(`${end}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-6+i);return businessDate(d)});const vals=dates.map(date=>state.data.sales.filter(s=>s.status!=='VOID'&&businessDate(s.created_at)===date).reduce((n,s)=>n+Number(s.total),0));const max=Math.max(...vals,1);return `<div class="bars">${dates.map((d,i)=>`<div class="bar-wrap" title="${d}: ${money(vals[i])}"><div class="bar" style="height:${Math.max(3,vals[i]/max*100)}%"></div><span class="bar-label">${d.slice(8)}/${d.slice(5,7)}</span></div>`).join('')}</div>`}


function salePage(){const products=state.data.products.filter(p=>p.active&&p.name.toLowerCase().includes(state.search.toLowerCase()));const totals=calculateSale(state.cart,state.payments);page(`<div class="page-head"><div><h2>Nueva venta</h2><p>Elegí productos y registrá el cobro.</p></div><span class="badge ${state.data.cashSession?.status==='OPEN'?'ok':'warn'}">Caja ${state.data.cashSession?.status==='OPEN'?'abierta':'cerrada'}</span></div><div class="sale-layout"><section><div class="toolbar"><div class="search">${icon('Search')}<input id="product-search" placeholder="Buscar producto o código" value="${esc(state.search)}"></div></div><div class="product-picker">${products.map(p=>`<button class="product-tile" data-add="${p.id}"><span><span class="name">${esc(p.name)}</span><span class="stock">${esc(p.code)} · Stock: ${p.stock}</span></span><strong>${money(p.sale_price)}</strong></button>`).join('')||'<div class="empty"><strong>Sin productos</strong>Cargá tu primer producto para vender.</div>'}</div></section><aside class="card cart"><div class="card-head"><h3>Detalle de la venta</h3><span class="badge neutral">${state.cart.reduce((a,l)=>a+l.quantity,0)} unidades</span></div>${state.cart.length?state.cart.map(l=>`<div class="cart-line"><div><strong>${esc(l.name)}</strong><div class="muted">${money(l.unit_price)} c/u</div></div><div class="qty"><button data-dec="${l.key}">−</button><strong>${l.quantity}</strong><button data-inc="${l.key}">+</button></div><strong>${money(l.unit_price*l.quantity)}</strong></div>`).join(''):'<div class="empty"><strong>Venta vacía</strong>Seleccioná uno o más productos.</div>'}<div style="margin-top:16px"><div class="summary-row"><span>Subtotal</span><span>${money(totals.subtotal)}</span></div><div class="summary-row total"><span>Total</span><span>${money(totals.total)}</span></div></div><div class="payment-list">${state.payments.map((p,i)=>`<div class="payment-row"><select data-pay-method="${i}"><option value="CASH" ${p.method==='CASH'?'selected':''}>Efectivo</option><option value="TRANSFER" ${p.method==='TRANSFER'?'selected':''}>Transferencia</option><option value="CARD" ${p.method==='CARD'?'selected':''}>POSNET/Tarjeta</option></select><input data-pay-amount="${i}" type="number" min="0" step="0.01" value="${p.amount||''}" placeholder="Importe"><button class="icon-btn" data-remove-pay="${i}">${icon('X')}</button></div>`).join('')}</div><button class="btn btn-soft btn-block" id="add-payment">${icon('Plus')} Agregar medio de pago</button><button class="btn btn-primary btn-block" id="finish-sale" style="margin-top:10px" ${!state.cart.length?'disabled':''}>Confirmar venta · ${money(totals.total)}</button></aside></div>`);bindSale();}
function bindSale(){document.querySelector('#product-search').oninput=e=>{state.search=e.target.value;salePage();hydrateIcons()};document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=state.data.products.find(x=>x.id===b.dataset.add);chooseSaleVariant(p)});document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));document.querySelectorAll('[data-pay-method]').forEach(s=>s.onchange=()=>state.payments[Number(s.dataset.payMethod)].method=s.value);document.querySelectorAll('[data-pay-amount]').forEach(i=>i.oninput=()=>state.payments[Number(i.dataset.payAmount)].amount=Number(i.value));document.querySelectorAll('[data-remove-pay]').forEach(b=>b.onclick=()=>{if(state.payments.length>1)state.payments.splice(Number(b.dataset.removePay),1);salePage();hydrateIcons()});document.querySelector('#add-payment').onclick=()=>{state.payments.push({method:'TRANSFER',amount:0});salePage();hydrateIcons()};document.querySelector('#finish-sale').onclick=finishSale;}
function changeQty(id,n){const l=state.cart.find(x=>x.key===id);l.quantity+=n;if(l.quantity<=0)state.cart=state.cart.filter(x=>x!==l);if(state.payments.length===1)state.payments[0].amount=calculateSale(state.cart,[]).total;salePage();hydrateIcons()}
async function finishSale(){const t=calculateSale(state.cart,state.payments);if(Math.abs(t.difference)>.009)return toast(`El cobro debe sumar ${money(t.total)}`);if(state.data.demo){toast('Modo demostración: conectá Supabase para guardar');return}const button=document.querySelector('#finish-sale');button.disabled=true;try{await createSale({lines:state.cart.map(({product_id,variant_id,quantity,unit_price,discount})=>({product_id,variant_id,quantity,unit_price,discount})),payments:state.payments});state.cart=[];state.payments=[{method:'CASH',amount:0}];state.data=await loadAppData();toast('Venta guardada');renderShell()}catch(e){button.disabled=false;toast(e.message)}}

function productsPage(){page(`<div class="page-head"><div><h2>Productos</h2><p>Catálogo, precios y estado.</p></div><button class="btn btn-primary" id="new-product">${icon('Plus')} Nuevo producto</button></div>${tableProducts()}`);document.querySelector('#new-product').onclick=()=>openProductModal();if(state.data.profile.role==='ADMIN'){document.querySelectorAll('[data-product-variants]').forEach(b=>b.onclick=()=>variantsModal(b.dataset.productVariants))}else{document.querySelector('#new-product').disabled=true}}
function tableProducts(){return `<div class="table-wrap"><table><thead><tr><th>Código</th><th>Producto</th><th>Categoría</th><th>Precio</th><th>Stock</th><th>Estado</th></tr></thead><tbody>${state.data.products.map(p=>`<tr><td>${esc(p.code)}</td><td><strong>${esc(p.name)}</strong>${state.data.profile.role==='ADMIN'&&p.product_type==='SIMPLE'?` <button class="btn btn-soft" data-product-variants="${p.id}">Variantes</button>`:''}</td><td>${esc(p.category_name||'Sin categoría')}</td><td class="money">${money(p.sale_price)}</td><td><span class="badge ${Number(p.stock)<=Number(p.min_stock)?'warn':'ok'}">${p.stock}</span></td><td><span class="badge ${p.active?'ok':'neutral'}">${p.active?'Activo':'Inactivo'}</span></td></tr>`).join('')}</tbody></table></div>`}
function openProductModal(){if(state.data.profile.role!=='ADMIN')return toast('Requiere ADMIN');modal(`<div class="modal-head"><h3>Nuevo producto</h3><button class="icon-btn" data-close>${icon('X')}</button></div><form id="product-form" class="form-grid"><div class="field span-2"><label>Nombre</label><input name="name" required></div><div class="field"><label>Categoría</label><select name="category_name"><option>Pestañas y bandejas</option><option>Adhesivos y preparación</option><option>Pinzas y herramientas</option><option>Higiene, accesorios y descartables</option><option>Kits</option></select></div><div class="field"><label>Precio de venta</label><input name="sale_price" type="number" min="0" step="0.01" required></div><div class="field"><label>Stock mínimo</label><input name="min_stock" type="number" min="0" value="0"></div><div class="field"><label>Tipo</label><select name="product_type"><option value="SIMPLE">Producto simple</option><option value="KIT_COMPONENTS">Kit con componentes</option><option value="KIT_OWN_STOCK">Kit con stock propio</option></select></div><div class="modal-actions span-2"><button class="btn btn-soft" type="button" data-close>Cancelar</button><button class="btn btn-primary">Guardar producto</button></div></form>`);document.querySelector('#product-form').onsubmit=async e=>{e.preventDefault();if(state.data.demo)return toast('Conectá Supabase para guardar');const f=Object.fromEntries(new FormData(e.currentTarget));f.sale_price=Number(f.sale_price);f.min_stock=Number(f.min_stock);f.active=true;try{await createProduct(f);closeModal();state.data=await loadAppData();productsPage();hydrateIcons();toast('Producto creado')}catch(err){toast(err.message)}}}

function stockPage(){const low=state.data.products.filter(p=>Number(p.stock)<=Number(p.min_stock));page(`<div class="page-head"><div><h2>Stock y lotes FIFO</h2><p>Entradas, vencimientos y costos pendientes.</p></div><button class="btn btn-primary" id="new-stock">${icon('Plus')} Registrar entrada</button></div>${low.some(p=>Number(p.stock)<0)?'<div class="notice danger">Hay productos con stock negativo. Sus costos se completarán con las próximas entradas.</div>':''}<div class="metric-grid"><article class="metric"><div class="metric-top">Productos activos</div><div class="metric-value">${state.data.products.length}</div></article><article class="metric"><div class="metric-top">Unidades disponibles</div><div class="metric-value">${state.data.products.reduce((a,p)=>a+Number(p.stock||0),0)}</div></article><article class="metric"><div class="metric-top">Stock bajo</div><div class="metric-value">${low.length}</div></article><article class="metric"><div class="metric-top">Costos pendientes</div><div class="metric-value">${state.data.stock.filter(l=>l.unit_cost==null&&state.data.receipts.find(r=>r.id===l.receipt_id)?.status==='ACTIVE').length}</div></article></div>${tableProducts()}`);document.querySelector('#new-stock').onclick=openStockModal;if(state.data.profile.role==='ADMIN'){showLotCosts();showReceipts();document.querySelectorAll('[data-product-variants]').forEach(b=>b.onclick=()=>variantsModal(b.dataset.productVariants));}else{document.querySelector('#new-stock').disabled=true}}
function openStockModal(){if(state.data.profile.role!=='ADMIN')return toast('Requiere ADMIN');modal(`<div class="modal-head"><h3>Nueva entrada de stock</h3><button class="icon-btn" data-close>${icon('X')}</button></div><div class="notice warn">Registrar stock no genera una salida de caja. El pago se carga por separado en Compras.</div><form id="stock-form" class="form-grid"><div class="field span-2"><label>Producto</label><select name="product_id" required>${state.data.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field span-2"><label>Variante</label><select name="variant_id" id="stock-variant"></select></div><div class="field"><label>Cantidad</label><input name="quantity" type="number" min=".001" step=".001" required></div><div class="field"><label>Costo total del lote</label><input name="total_cost" type="number" min="0" step=".01" placeholder="Dejar vacío si no se conoce"></div><div class="field"><label>Número de lote</label><input name="lot_number"></div><div class="field"><label>Vencimiento</label><input name="expires_at" type="date"></div><div class="modal-actions span-2"><button class="btn btn-soft" type="button" data-close>Cancelar</button><button class="btn btn-primary">Registrar entrada</button></div></form>`);const productSelect=document.querySelector('#stock-form [name=product_id]');const fillVariants=()=>{const variants=state.data.variants.filter(v=>v.product_id===productSelect.value&&v.active);const select=document.querySelector('#stock-variant');select.innerHTML=variants.length?'<option value="">Seleccionar variante</option>'+variants.map(v=>`<option value="${v.id}">${esc(variantName(v))}</option>`).join(''):'<option value="">Sin variantes</option>';select.required=Boolean(variants.length)};productSelect.onchange=fillVariants;fillVariants();document.querySelector('#stock-form').onsubmit=async e=>{e.preventDefault();if(state.data.demo)return toast('Conectá Supabase para guardar');const f=Object.fromEntries(new FormData(e.currentTarget));f.quantity=Number(f.quantity);f.total_cost=f.total_cost===''?null:Number(f.total_cost);try{await createStockReceipt(f);closeModal();state.data=await loadAppData();stockPage();hydrateIcons();toast('Entrada registrada')}catch(err){toast(err.message)}}}

function cashPage(){const s=state.data.cashSession;const sales=dailySales();const by={CASH:0,TRANSFER:0,CARD:0};sales.flatMap(x=>x.sale_payments||[]).forEach(p=>by[p.method]=(by[p.method]||0)+Number(p.amount));page(`<div class="page-head"><div><h2>Caja del día</h2><p>Cobros, ingresos, retiros y arqueo.</p></div><span class="badge ${s?.status==='OPEN'?'ok':'neutral'}">${s?.status==='OPEN'?'Caja abierta':'Caja cerrada'}</span></div><section class="metric-grid"><article class="metric"><div class="metric-top">Efectivo</div><div class="metric-value">${money(by.CASH)}</div></article><article class="metric"><div class="metric-top">Transferencias</div><div class="metric-value">${money(by.TRANSFER)}</div></article><article class="metric"><div class="metric-top">POSNET/Tarjeta</div><div class="metric-value">${money(by.CARD)}</div></article><article class="metric"><div class="metric-top">Efectivo esperado</div><div class="metric-value">${money(cashExpected(s,state.data.cashMovements))}</div></article></section><article class="card"><div class="card-head"><h3>Control de caja</h3></div><div class="summary-row"><span>Efectivo inicial</span><strong>${money(s?.opening_cash||0)}</strong></div><div class="summary-row"><span>Ventas en efectivo</span><strong>${money(by.CASH)}</strong></div><div class="summary-row total"><span>Esperado</span><span>${money(cashExpected(s,state.data.cashMovements))}</span></div><div class="toolbar" style="margin-top:18px">${s?.status==='OPEN'?`<button class="btn btn-primary" id="close-cash">Cerrar y arquear caja</button>`:`<button class="btn btn-primary" id="open-cash">Abrir caja</button>`}</div></article>`);document.querySelector('#open-cash')?.addEventListener('click',openCashModal);document.querySelector('#close-cash')?.addEventListener('click',closeCashModal)}
function openCashModal(){modal(`<div class="modal-head"><h3>Abrir caja</h3><button class="icon-btn" data-close>${icon('X')}</button></div><form id="cash-open-form"><div class="field"><label>Efectivo inicial</label><input name="amount" type="number" min="0" step=".01" value="0" required></div><div class="modal-actions"><button type="button" class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-primary">Abrir caja</button></div></form>`);document.querySelector('#cash-open-form').onsubmit=async e=>{e.preventDefault();if(state.data.demo)return toast('Conectá Supabase para guardar');try{await openCash(Number(new FormData(e.currentTarget).get('amount')));closeModal();state.data=await loadAppData();cashPage();hydrateIcons();toast('Caja abierta')}catch(err){toast(err.message)}}}
function closeCashModal(){modal(`<div class="modal-head"><h3>Cerrar caja</h3><button class="icon-btn" data-close>${icon('X')}</button></div><form id="cash-close-form"><div class="field"><label>Efectivo contado</label><input name="amount" type="number" min="0" step=".01" required></div><div class="modal-actions"><button type="button" class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-primary">Confirmar arqueo</button></div></form>`);document.querySelector('#cash-close-form').onsubmit=async e=>{e.preventDefault();if(state.data.demo)return toast('Conectá Supabase para guardar');try{await closeCash(Number(new FormData(e.currentTarget).get('amount')));closeModal();state.data=await loadAppData();cashPage();hydrateIcons();toast('Caja cerrada')}catch(err){toast(err.message)}}}
function expensesPage(){
 if(state.data.profile.role!=='ADMIN'){page('<div class="notice">Compras y gastos requieren ADMIN.</div>');return;}
 const kinds={OPERATING:'Gasto del negocio',PURCHASE:'Compra de mercadería',LOAN:'Cuota de crédito'};
 page(`<div class="page-head"><div><h2>Costos y gastos</h2><p>Compras, gastos y cuotas. El stock se registra por separado.</p></div><button class="btn btn-primary" id="new-expense">Nuevo movimiento</button></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Concepto</th><th>Tipo</th><th>Vencimiento</th><th>Estado</th><th>Importe</th><th>Acciones</th></tr></thead><tbody>${state.data.expenses.map(x=>`<tr><td>${esc(x.incurred_at)}</td><td>${esc(x.description)}</td><td>${esc(kinds[x.kind]||x.kind)}</td><td>${esc(x.due_at||'—')}</td><td>${x.status==='VOID'?'Anulado':x.status==='PAID'?'Pagado':'Pendiente'}</td><td>${money(x.amount)}</td><td>${x.status==='PENDING'?`<button class="btn btn-soft" data-pay-expense="${x.id}">Pagar</button>`:''}${x.status!=='VOID'?`<button class="btn btn-soft" data-void-expense="${x.id}">Anular</button>`:''}</td></tr>`).join('')||'<tr><td colspan="7">Sin movimientos</td></tr>'}</tbody></table></div>`);
 document.querySelector('#new-expense').onclick=openExpenseModal;
 document.querySelectorAll('[data-pay-expense]').forEach(b=>b.onclick=()=>expenseActionModal(b.dataset.payExpense,false));
 document.querySelectorAll('[data-void-expense]').forEach(b=>b.onclick=()=>expenseActionModal(b.dataset.voidExpense,true));
}
function expenseActionModal(id,voiding){
 modal(`<div class="modal-head"><h3>${voiding?'Anular movimiento':'Registrar pago'}</h3><button class="icon-btn" data-close>×</button></div><form id="expense-action">${voiding?'<div class="field"><label>Motivo</label><input name="reason" required></div>':'<div class="field"><label>Medio de pago</label><select name="method" required><option value="">Seleccionar</option><option value="CASH">Efectivo</option><option value="TRANSFER">Transferencia</option><option value="CARD">POSNET/Tarjeta</option></select></div><div class="field"><label>Fecha y hora del pago (Argentina)</label><input name="paid_at" type="datetime-local" required></div>'}<div class="modal-actions"><button class="btn btn-soft" type="button" data-close>Cancelar</button><button class="btn btn-primary">Confirmar</button></div></form>`);
 document.querySelector('#expense-action').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const button=e.currentTarget.querySelector('button[type="submit"],button.btn-primary');button.disabled=true;try{if(voiding)await voidExpense(id,f.reason);else await payExpense(id,f.method,argentinaTimestamp(f.paid_at));closeModal();state.data=await loadAppData();expensesPage();hydrateIcons();toast(voiding?'Movimiento anulado':'Pago registrado')}catch(err){button.disabled=false;toast(err.message)}};
}

function openExpenseModal(){modal(`<div class="modal-head"><h3>Nuevo costo o gasto</h3><button class="icon-btn" data-close>${icon('X')}</button></div><form id="expense-form" class="form-grid"><div class="field span-2"><label>Concepto</label><input name="description" required placeholder="Ej.: bolsas y embalaje"></div><div class="field"><label>Tipo</label><select name="kind"><option value="OPERATING">Gasto del negocio</option><option value="PURCHASE">Compra de mercadería</option><option value="LOAN">Cuota de crédito</option></select></div><div class="field"><label>Importe</label><input name="amount" type="number" min="0" step=".01" required></div><div class="field"><label>Fecha</label><input name="incurred_at" type="date" value="${todayISO()}" required></div><div class="field"><label>Vencimiento</label><input name="due_at" type="date"></div><div class="field"><label>Estado</label><select name="status"><option value="PENDING">Pendiente</option><option value="PAID">Pagado</option></select></div><div class="field"><label>Medio de pago (salida en la caja abierta)</label><select name="payment_method"><option value="">Seleccionar</option><option value="CASH">Efectivo</option><option value="TRANSFER">Transferencia</option><option value="CARD">POSNET/Tarjeta</option></select></div><div class="field"><label>Fecha y hora del pago (Argentina)</label><input name="paid_at" type="datetime-local"></div><div class="modal-actions span-2"><button type="button" class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-primary">Guardar</button></div></form>`);document.querySelector('#expense-form').onsubmit=async e=>{e.preventDefault();if(state.data.demo)return toast('Conectá Supabase para guardar');const f=Object.fromEntries(new FormData(e.currentTarget));f.amount=Number(f.amount);f.due_at=f.due_at||null;try{if(f.status==='PAID'){if(!f.payment_method||!f.paid_at)throw new Error('Indicá medio, fecha y hora del pago');f.paid_at=argentinaTimestamp(f.paid_at)}else{f.paid_at=null;f.payment_method=null}await createExpense(f);closeModal();state.data=await loadAppData();expensesPage();hydrateIcons();toast('Movimiento guardado')}catch(err){toast(err.message)}}}
function appointmentsPage(){page(`<div class="page-head"><div><h2>Agenda de turnos</h2><p>Servicios, señas, saldos y estado de cada cita.</p></div><button class="btn btn-primary" id="new-appointment">${icon('Plus')} Nuevo turno</button></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Clienta</th><th>Servicio</th><th>Seña</th><th>Saldo</th><th>Estado</th></tr></thead><tbody>${state.data.appointments.length?state.data.appointments.map(a=>`<tr><td>${new Date(a.starts_at).toLocaleString('es-AR')}</td><td>${esc(a.customers?.full_name||'—')}</td><td>${esc(a.products?.name||'Servicio')}</td><td class="money">${money(a.deposit_amount)}</td><td class="money">${money(a.balance_amount)}</td><td><span class="badge neutral">${esc(a.status)}</span></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty"><strong>Sin turnos</strong>Creá el primer turno cuando tengas una reserva.</div></td></tr>'}</tbody></table></div>`);document.querySelector('#new-appointment').onclick=openAppointmentModal;}
function openAppointmentModal(){modal(`<div class="modal-head"><h3>Nuevo turno</h3><button class="icon-btn" data-close>${icon('X')}</button></div><form id="appointment-form" class="form-grid"><div class="field span-2"><label>Clienta</label><select name="customer_id"><option value="NEW">Crear nueva clienta</option>${state.data.customers.map(c=>`<option value="${c.id}">${esc(c.full_name)}</option>`).join('')}</select></div><div class="field span-2" id="new-customer"><label>Nombre de la clienta</label><input name="customer_name"></div><div class="field"><label>Fecha y hora</label><input name="starts_at" type="datetime-local" required></div><div class="field"><label>Servicio</label><select name="service_product_id"><option value="">Sin cargar todavía</option>${state.data.products.filter(p=>p.product_type==='SERVICE').map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Seña</label><input name="deposit_amount" type="number" min="0" step=".01" value="0"></div><div class="field"><label>Saldo</label><input name="balance_amount" type="number" min="0" step=".01" value="0"></div><div class="modal-actions span-2"><button type="button" class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-primary">Guardar turno</button></div></form>`);document.querySelector('#appointment-form').onsubmit=async e=>{e.preventDefault();if(state.data.demo)return toast('Conectá Supabase para guardar');const f=Object.fromEntries(new FormData(e.currentTarget));try{if(f.customer_id==='NEW'){if(!f.customer_name)throw new Error('Ingresá el nombre de la clienta');const c=await createCustomer({full_name:f.customer_name});f.customer_id=c.id}delete f.customer_name;f.service_product_id=f.service_product_id||null;f.deposit_amount=Number(f.deposit_amount);f.balance_amount=Number(f.balance_amount);f.status='RESERVED';await createAppointment(f);closeModal();state.data=await loadAppData();appointmentsPage();hydrateIcons();toast('Turno guardado')}catch(err){toast(err.message)}}}
function studentsPage(){page(`<div class="page-head"><div><h2>Alumnas y cursos</h2><p>Inscripciones, pagos, asistencia y certificados.</p></div><div class="toolbar"><button class="btn btn-soft" id="new-course">Nuevo curso</button><button class="btn btn-primary" id="new-enrollment">${icon('Plus')} Inscribir alumna</button></div></div><section class="metric-grid"><article class="metric"><div class="metric-top">Cursos</div><div class="metric-value">${state.data.courses.length}</div></article><article class="metric"><div class="metric-top">Inscripciones</div><div class="metric-value">${state.data.enrollments.length}</div></article></section><div class="table-wrap"><table><thead><tr><th>Alumna</th><th>Curso</th><th>Importe</th><th>Estado</th><th>Inscripción</th></tr></thead><tbody>${state.data.enrollments.length?state.data.enrollments.map(e=>`<tr><td>${esc(e.customers?.full_name)}</td><td>${esc(e.courses?.name)}</td><td class="money">${money(e.total_amount)}</td><td><span class="badge ok">${esc(e.status)}</span></td><td>${new Date(e.enrolled_at).toLocaleDateString('es-AR')}</td></tr>`).join(''):'<tr><td colspan="5"><div class="empty"><strong>Sin alumnas inscriptas</strong>Creá un curso y luego registrá la inscripción.</div></td></tr>'}</tbody></table></div>`);document.querySelector('#new-course').onclick=openCourseModal;document.querySelector('#new-enrollment').onclick=openEnrollmentModal;}
function openCourseModal(){modal(`<div class="modal-head"><h3>Nuevo curso</h3><button class="icon-btn" data-close>${icon('X')}</button></div><form id="course-form" class="form-grid"><div class="field span-2"><label>Nombre</label><input name="name" required></div><div class="field"><label>Inicio</label><input name="starts_at" type="datetime-local"></div><div class="field"><label>Precio</label><input name="price" type="number" min="0" step=".01"></div><div class="modal-actions span-2"><button type="button" class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-primary">Guardar curso</button></div></form>`);document.querySelector('#course-form').onsubmit=async e=>{e.preventDefault();if(state.data.demo)return toast('Conectá Supabase para guardar');const f=Object.fromEntries(new FormData(e.currentTarget));f.price=f.price===''?null:Number(f.price);try{await createCourse(f);closeModal();state.data=await loadAppData();studentsPage();hydrateIcons();toast('Curso creado')}catch(err){toast(err.message)}}}
function openEnrollmentModal(){modal(`<div class="modal-head"><h3>Inscribir alumna</h3><button class="icon-btn" data-close>${icon('X')}</button></div>${!state.data.courses.length?'<div class="notice warn">Primero tenés que crear un curso.</div>':''}<form id="enrollment-form" class="form-grid"><div class="field span-2"><label>Curso</label><select name="course_id" required>${state.data.courses.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field span-2"><label>Alumna</label><select name="customer_id"><option value="NEW">Crear nueva alumna</option>${state.data.customers.map(c=>`<option value="${c.id}">${esc(c.full_name)}</option>`).join('')}</select></div><div class="field span-2"><label>Nombre si es nueva</label><input name="customer_name"></div><div class="field"><label>Importe total</label><input name="total_amount" type="number" min="0" step=".01" value="0"></div><div class="modal-actions span-2"><button type="button" class="btn btn-soft" data-close>Cancelar</button><button class="btn btn-primary" ${!state.data.courses.length?'disabled':''}>Inscribir</button></div></form>`);document.querySelector('#enrollment-form').onsubmit=async e=>{e.preventDefault();if(state.data.demo)return toast('Conectá Supabase para guardar');const f=Object.fromEntries(new FormData(e.currentTarget));try{if(f.customer_id==='NEW'){if(!f.customer_name)throw new Error('Ingresá el nombre de la alumna');const c=await createCustomer({full_name:f.customer_name});f.customer_id=c.id}delete f.customer_name;f.total_amount=Number(f.total_amount);f.status='ACTIVE';await createEnrollment(f);closeModal();state.data=await loadAppData();studentsPage();hydrateIcons();toast('Alumna inscripta')}catch(err){toast(err.message)}}}
function reportsPage(){
 if(state.data.profile.role!=='ADMIN'){page('<div class="notice">Los informes de costos y rentabilidad están disponibles para ADMIN.</div>');return;}
 const month=state.reportMonth||todayISO().slice(0,7);const year=month.slice(0,4);
 const columns=[['revenue','Ventas'],['operations','Operaciones'],['cogs','COGS FIFO'],['gross','Margen bruto'],['commissions','Comisiones'],['purchases','Compras pagadas'],['expenses','Gastos'],['operating','Resultado operativo'],['loans','Cuotas'],['afterLoans','Resultado después de cuotas'],['flow','Flujo'],['flowAfterLoans','Flujo después de cuotas']];
 const months=new Set();
 const add=date=>{if(date){const m=businessDate(date).slice(0,7);if(m.startsWith(year))months.add(m)}};
 state.data.sales.filter(s=>s.status!=='VOID').forEach(s=>add(s.created_at));
 state.data.expenses.filter(e=>e.status!=='VOID').forEach(e=>{add(e.incurred_at);add(e.paid_at)});
 const value=(r,key)=>key==='operations'?r[key]:r[key]==null?'Pendiente':money(r[key]);
 const row=(label,r)=>`<tr><td>${esc(label)}</td>${columns.map(([k])=>`<td>${value(r,k)}</td>`).join('')}</tr>`;
 const r=periodSummary(state.data,month);
 page(`<div class="page-head"><div><h2>Informes</h2><p>Rentabilidad por fecha del movimiento; flujo por fecha de pago. ARS.</p></div><input id="report-month" type="month" value="${month}"></div>${r.pending||r.cashPending?'<div class="notice warn">Hay costos o fechas de pago pendientes. Los resultados afectados no se estiman.</div>':''}<article class="card"><h3>Control mensual</h3><div style="overflow-x:auto"><table><thead><tr><th>Mes</th>${columns.map(([,label])=>`<th>${label}</th>`).join('')}</tr></thead><tbody>${row(month,r)}</tbody></table></div></article><article class="card"><h3>Resumen anual ${year}</h3><div style="overflow-x:auto"><table><thead><tr><th>Mes</th>${columns.map(([,label])=>`<th>${label}</th>`).join('')}</tr></thead><tbody>${[...months].sort().map(m=>row(m,periodSummary(state.data,m))).join('')}${row('Total anual',periodSummary(state.data,year))}</tbody></table></div></article>`);
 document.querySelector('#report-month').onchange=e=>{if(e.target.value){state.reportMonth=e.target.value;reportsPage()}};
}

function auditPage(){const rows=state.data.audit;page(`<div class="page-head"><div><h2>Auditoría</h2><p>Historial de operaciones registradas.</p></div></div><div class="table-wrap"><table><thead><tr><th>Fecha y hora</th><th>Usuario</th><th>Acción</th><th>Entidad</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.occurred_at).toLocaleString('es-AR')}</td><td>${esc(x.profiles?.full_name||'Sistema')}</td><td>${esc(x.action)}</td><td>${esc(x.entity_type)}</td></tr>`).join('')}</tbody></table></div>`)}
function moduleEmpty(title,copy,ico,action){return `<div class="page-head"><div><h2>${title}</h2><p>${copy}</p></div><button class="btn btn-primary">${icon('Plus')} ${action}</button></div><article class="card"><div class="empty">${icon(ico)}<strong>Aún no hay registros</strong>Este módulo está preparado para tus datos reales.</div></article>`}
function modal(html){document.querySelector('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal">${html}</section></div>`;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal);document.querySelector('.modal-backdrop').addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()});hydrateIcons();}
function closeModal(){document.querySelector('#modal-root').innerHTML=''}

let recovering=recoveryRequested;
if(supabase)supabase.auth.onAuthStateChange(event=>{
 if(event==='PASSWORD_RECOVERY'){recovering=true;sessionStorage.setItem('lashby-recovery','1');setTimeout(()=>recoveryView(true),0);}
 if(event==='SIGNED_OUT'){sessionStorage.removeItem('lashby-recovery');}
});
(async()=>{
 if(authRedirectError){history.replaceState(null,'',location.pathname);loginView();toast('El enlace es inválido o venció. Solicitá uno nuevo desde Crear o recuperar contraseña.');return;}
 const s=await session();
 if(recovering||(s&&sessionStorage.getItem('lashby-recovery')==='1')){recoveryView(Boolean(s));return;}
 s?boot():loginView();
})();

function authCard(title,description,fields,submitLabel){
 app.innerHTML=`<main class="login-shell"><section class="login-brand"><div class="brand-mark"><img class="brand-logo" src="${lashbyLogo}" alt="Logo de Lashby Beauty Eyelashes" width="96" height="96"><span>Lashby Academia</span></div><div class="login-copy"><h1>Tu acceso a Lashby</h1></div></section><section class="login-panel"><form class="login-card" id="auth-form"><span class="eyebrow">Acceso seguro</span><h2>${esc(title)}</h2><p>${esc(description)}</p>${fields}<p id="auth-message" role="status" aria-live="polite"></p><button class="btn btn-primary btn-block" type="submit">${esc(submitLabel)}</button><button class="btn btn-soft btn-block" type="button" id="back-login" style="margin-top:12px">Volver al ingreso</button></form></section></main>`;
 document.querySelector('#back-login').onclick=async()=>{recovering=false;sessionStorage.removeItem('lashby-recovery');await signOut();loginView();};
 return document.querySelector('#auth-form');
}
function resetRequestView(){
 const form=authCard('Crear o recuperar contraseña','Ingresá el correo de tu usuario de Lashby. Te enviaremos un enlace para elegir tu contraseña.',`<div class="field"><label for="reset-email">Correo electrónico</label><input id="reset-email" name="email" type="email" autocomplete="username" required></div>`,'Enviar enlace');
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button[type="submit"]');button.disabled=true;const message=document.querySelector('#auth-message');try{await requestPasswordReset(new FormData(form).get('email').trim());message.textContent='Si el correo corresponde a un usuario, recibirás un enlace. Abrí el correo más reciente y usá el enlace una sola vez.';}catch(err){message.textContent='No se pudo enviar el enlace. '+err.message;button.disabled=false;}};
}
function recoveryView(valid){
 const form=authCard('Elegí tu contraseña',valid?'Escribí tu nueva contraseña dos veces.':'El enlace no tiene una sesión válida. Volvé al ingreso y solicitá un enlace nuevo.',`<div class="field"><label for="new-password">Nueva contraseña</label><input id="new-password" name="password" type="password" autocomplete="new-password" minlength="8" required></div><div class="field"><label for="confirm-password">Repetir contraseña</label><input id="confirm-password" name="confirm" type="password" autocomplete="new-password" minlength="8" required></div>`,'Guardar contraseña');
 const button=form.querySelector('button[type="submit"]');button.disabled=!valid;
 form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form);const message=document.querySelector('#auth-message');if(f.get('password')!==f.get('confirm')){message.textContent='Las contraseñas no coinciden.';return;}button.disabled=true;try{await updatePassword(f.get('password'));recovering=false;sessionStorage.removeItem('lashby-recovery');history.replaceState(null,'',location.pathname);form.reset();await signOut();loginView();toast('Contraseña guardada. Ya podés ingresar con tu correo y contraseña.');}catch(err){message.textContent='No se pudo guardar la contraseña. '+err.message;button.disabled=false;}};
}

function showLotCosts(){
 const host=document.querySelector('#content');
 if(!host)return;
 host.insertAdjacentHTML('beforeend',`<article class="card"><h3>Costos de lotes</h3>${state.data.stock.map(l=>`<div class="cart-line"><div><strong>${esc(l.products?.name||'Producto')}</strong><div>${esc(l.lot_number||'Sin número de lote')} · ${l.initial_quantity} unidades</div></div>${state.data.receipts.find(r=>r.id===l.receipt_id)?.status==='VOID'?'<span class="badge neutral">Entrada anulada</span>':l.unit_cost==null?`<button class="btn btn-soft" data-lot-cost="${l.id}">Completar costo pendiente</button>`:`<span>${money(l.unit_cost)} por unidad</span>`}</div>`).join('')||'<p>Sin entradas</p>'}</article>`);
 document.querySelectorAll('[data-lot-cost]').forEach(b=>b.onclick=()=>{
  const id=b.dataset.lotCost;
  modal('<div class="modal-head"><h3>Completar costo del lote</h3><button class="icon-btn" data-close>×</button></div><p>Ingresá el costo total real. Se actualizarán los costos pendientes de las unidades ya vendidas de este lote.</p><form id="lot-cost-form"><div class="field"><label>Costo total</label><input name="total" type="number" min="0" step=".01" required></div><button class="btn btn-primary">Guardar costo</button></form>');
  document.querySelector('#lot-cost-form').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;try{await completeLotCost(id,Number(new FormData(e.currentTarget).get('total')));closeModal();state.data=await loadAppData();stockPage();hydrateIcons();toast('Costo completado')}catch(err){button.disabled=false;toast(err.message)}};
 });
}

function variantName(v){return [v.curve,v.thickness,v.length,v.color].filter(Boolean).join(' · ')||'Variante';}
function chooseSaleVariant(product){
 const variants=state.data.variants.filter(v=>v.product_id===product.id&&v.active);
 if(!variants.length)return addCartProduct(product,null);
 modal(`<div class="modal-head"><h3>${esc(product.name)}</h3><button class="icon-btn" data-close>×</button></div><div class="field"><label>Variante</label><select id="sale-variant">${variants.map(v=>`<option value="${v.id}">${esc(variantName(v))}</option>`).join('')}</select></div><button class="btn btn-primary" id="add-variant">Agregar</button>`);
 document.querySelector('#add-variant').onclick=()=>{const variant=variants.find(v=>v.id===document.querySelector('#sale-variant').value);closeModal();addCartProduct(product,variant)};
}
function addCartProduct(product,variant){
 const key=product.id+':'+(variant?.id||'');const line=state.cart.find(l=>l.key===key);
 if(line)line.quantity++;else state.cart.push({key,product_id:product.id,variant_id:variant?.id||null,name:product.name+(variant?' · '+variantName(variant):''),quantity:1,unit_price:Number(product.sale_price),discount:0});
 if(state.payments.length===1)state.payments[0].amount=calculateSale(state.cart,[]).total;
 salePage();hydrateIcons();
}

function variantsModal(productId){
 const variants=state.data.variants.filter(v=>v.product_id===productId);
 modal(`<div class="modal-head"><h3>Variantes del producto</h3><button class="icon-btn" data-close>×</button></div><p>${variants.map(v=>esc(variantName(v))).join('<br>')||'Sin variantes'}</p><form id="variant-form" class="form-grid">${[['curve','Curva'],['thickness','Grosor'],['length','Largo'],['color','Color']].map(([key,label])=>`<div class="field"><label>${label}</label><input name="${key}"></div>`).join('')}<div class="modal-actions span-2"><button class="btn btn-primary">Agregar variante</button></div></form>`);
 document.querySelector('#variant-form').onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));if(!Object.values(values).some(v=>v.trim()))return toast('Indicá al menos una característica');const button=e.currentTarget.querySelector('button');button.disabled=true;try{await createVariant({product_id:productId,...Object.fromEntries(Object.entries(values).map(([k,v])=>[k,v.trim()||null]))});state.data=await loadAppData();variantsModal(productId);hydrateIcons()}catch(err){button.disabled=false;toast(err.message)}};
}

function salesHistoryPage(){
 const admin=state.data.profile.role==='ADMIN';
 page(`<div class="page-head"><div><h2>Historial de ventas</h2><p>Las operaciones anuladas se conservan y no participan en los totales.</p></div></div><div class="table-wrap"><table><thead><tr><th>Operación</th><th>Fecha Argentina</th><th>Productos</th><th>Total</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${state.data.sales.map(s=>`<tr><td>${esc(s.number)}</td><td>${esc(businessDate(s.created_at))}</td><td>${(s.sale_lines||[]).map(l=>esc(l.product_name)+' × '+Number(l.quantity)).join('<br>')}</td><td>${money(s.total)}</td><td>${s.status==='VOID'?`Anulada: ${esc(s.void_reason||'')}`:esc(s.status)}</td><td>${admin&&s.status!=='VOID'?`<button class="btn btn-soft" data-void-sale="${s.id}">Anular</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6">Sin ventas</td></tr>'}</tbody></table></div>`);
 document.querySelectorAll('[data-void-sale]').forEach(b=>b.onclick=()=>voidOperationModal('sale',b.dataset.voidSale));
}
function showReceipts(){
 document.querySelector('#content').insertAdjacentHTML('beforeend',`<article class="card"><h3>Historial de entradas</h3><div class="table-wrap"><table><thead><tr><th>Fecha Argentina</th><th>Productos</th><th>Estado</th><th>Motivo</th><th>Acción</th></tr></thead><tbody>${state.data.receipts.map(r=>`<tr><td>${esc(businessDate(r.received_at))}</td><td>${state.data.stock.filter(l=>l.receipt_id===r.id).map(l=>esc(l.products?.name||'Producto')+' × '+Number(l.initial_quantity)).join('<br>')}</td><td>${r.status==='VOID'?'Anulada':'Activa'}</td><td>${esc(r.void_reason||'—')}</td><td>${r.status==='ACTIVE'?`<button class="btn btn-soft" data-void-receipt="${r.id}">Anular</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5">Sin entradas</td></tr>'}</tbody></table></div></article>`);
 document.querySelectorAll('[data-void-receipt]').forEach(b=>b.onclick=()=>voidOperationModal('receipt',b.dataset.voidReceipt));
}
function voidOperationModal(kind,id){
 if(state.data.profile.role!=='ADMIN')return toast('Requiere autorización ADMIN');
 const sale=kind==='sale';
 modal(`<div class="modal-head"><h3>${sale?'Anular venta':'Anular entrada'}</h3><button class="icon-btn" data-close>×</button></div><p>${sale?'La venta se conserva para auditoría. Se revierten el cobro y las unidades vendidas.':'La entrada se conserva y se retiran sus cantidades del stock. Los costos de unidades ya vendidas se reasignan por FIFO; si falta stock o costo, quedan pendientes.'}</p><form id="void-operation"><div class="field"><label>Motivo de la anulación</label><textarea name="reason" required></textarea></div><div class="modal-actions"><button class="btn btn-soft" type="button" data-close>Cancelar</button><button class="btn btn-primary">Confirmar anulación</button></div></form>`);
 document.querySelector('#void-operation').onsubmit=async e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason').trim();if(!reason)return toast('Ingresá el motivo');const button=e.currentTarget.querySelector('.btn-primary');button.disabled=true;try{if(sale)await voidSale(id,reason);else await voidStockReceipt(id,reason);closeModal();state.data=await loadAppData();renderShell();toast(sale?'Venta anulada':'Entrada anulada')}catch(err){button.disabled=false;toast(err.message)}};
}
